name: deploy-dev
run-name: Deploy webapp/events for `${{ github.base_ref }}`
on:
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  STAGE: "dev"

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged == true }}
    env:
      FUNCTION_NAME: "pescle-insects-api-external"
      WORKDIR: backend
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get version from VERSION_API
        id: version
        run: |
          VERSION=$(head -n 1 VERSION_API)
          VERSION=`echo ${VERSION} | sed -e "s/[\r\n]\+//g"`
          echo "version_api=$VERSION" >> $GITHUB_OUTPUT
        shell: bash
      - uses: ./.github/actions/update-lambda
        with:
          alias: ${{ steps.version.outputs.version_api }}
          function_name: ${{ env.FUNCTION_NAME }}
          stage: ${{ env.STAGE }}
          tfstate_url: "s3://pescle-insects-terraform-state-${{ env.STAGE }}/infrastructure.tfstate"
          workdir: "${{ env.WORKDIR }}/lambroll"
      - run: |
          echo "tag=${{ env.STAGE }}-api-${{ steps.version.outputs.version_api }}"
      - uses: ./.github/actions/comment
        with:
          message: "Deploy api-${{ steps.version.outputs.version_api }} succeeded."
