name: hello
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name to greet"
        required: true
        default: "World"
jobs:
  hello:
    if: startsWith(inputs.name, 'World')
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: echo "Hello1, ${{ github.event.inputs.name }}!"
      - if: endsWith(inputs.name, 'END')
        run: exit 1

  success:
    needs: hello
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: echo "Hello2, ${{ needs.hello.result }}!"

  failure:
    needs: hello
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: echo "Hello3, ${{ needs.hello.result }}!"

  cancelled:
    needs: hello
    if: cancelled()
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: echo "Hello4, ${{ needs.hello.result }}!"

  always:
    needs: hello
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: echo "Hello4, ${{ needs.hello.result }}!"
